name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Generate xcodeproj
      run: swift package generate-xcodeproj

    - name: Run tests
      run: set -o pipefail && xcodebuild test -scheme swift-nio-mqtt-Package -destination name="iPhone 11" -enableCodeCoverage YES -derivedDataPath .build/derivedData | xcpretty
      
    - name: Install Slather
      run: gem install slather

    - name: Run Slather
      run: slather coverage -x --output-directory Slather/Report.xml --build-directory .build --scheme swift-nio-mqtt-Package swift-nio-mqtt.xcodeproj

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: Slather/Report.xml
